# Silent-install response file for IBM ILOG CPLEX Optimization Studio (Linux).
# Consumed by the installer via:  ./cplex_linux.bin -f cplex_silent.properties
# Installing implies acceptance of the IBM ILOG CPLEX licence terms.
INSTALLER_UI=silent
LICENSE_ACCEPTED=true
USER_INSTALL_DIR=/opt/ibm/ILOG/CPLEX_Studio
INSTALLER_LOCALE=en
